name: Unit Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_HOST: "localhost"
      DB_USER: "root"
      DB_PASSWORD: "password"
      DB_NAME: "tech4all"
    
          

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v2
      - name: create .env file
        run: echo "DB_HOST=$DB_HOST\nDB_USER=$DB_USER\nDB_PASSWORD=$DB_PASSWORD\nDB_NAME=$DB_NAME" > .env 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
        working-directory: server
      - name: Run tests
        run: npm test
        working-directory: server
